First cut of content.
lsst-sims/smtn-007 pull request #1
Opened 2016-11-11 16:54 UTC by mareuter

To view the document locally do the following.

1. Clone this repo and switch to the branch
1. Create a new conda environment (I called mine technote) using Python3
1. Activate the previously create environment
1. cd to the clone if not already there
1. Run _pip install -r requirements.txt_
1. Run _make html_
1. Navigate your browser to generated documentation

I'm mainly looking for feedback on the flow of the document. However, I'm happy to discuss the finer points of what goes into the interface.

2016-11-11 22:43 UTC, cathypetry commented
so far, if I go to

[cid:802CF7E5-5D35-4ACF-A1C2-88BB888D810E@lsst.local]

And I go to index.html - I just get - but there are no links.  Is this all?

[cid:EC0C3BBC-A733-4A3E-9AC9-ED2024020B14@lsst.local]


On Nov 11, 2016, at 9:54 AM, Michael Reuter <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1<https://github.com/lsst-sims/smtn-007/pull/1> to @cathypetry<https://github.com/cathypetry>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/lsst-sims/smtn-007/pull/1#event-856150363>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AIPDNp2_x7cwxyVMMi4NAz1ZN60twtNZks5q9J3jgaJpZM4Kv71F>.

2016-11-14 18:59 UTC, cathypetry commented on index.rst
> +The Simulated Observatory Control System (SOCS) is designed to work with the LSST Scheduler. However, this does not mean that other Schedulers can't be developed and interfaced with SOCS in order to
Perhaps we could make this a more positive statement by replacing the second sentence with "...LSST Scheduler, and it was also designed with the intent that other Schedulers could be developed and interfaced with SOCS in order to produce simulated surveys."

2016-11-14 19:03 UTC, cathypetry commented on index.rst
> +All information is currently mandatory due to the LSST Scheduler being responsible for the information. However, the new `Sims Survey Fields code`_ is destined end the need for a Scheduler to send th
"... is destined end the..."  should be "...is destined to end the..." (I think)

2016-11-14 19:04 UTC, cathypetry commented on index.rst
> -     Caption text.
"field Id" should be "field ID" or "unique field identifier"

2016-11-14 19:10 UTC, cathypetry commented on index.rst
> +From Scheduler Topics
It took me a  second to interpret  what this meant - I like that it is short, however.   Maybe make it a hyphenated adjective:  "From-Scheduler Topics" ?  And the same for To Scheduler Topics.

2016-11-14 19:16 UTC, cathypetry commented on index.rst
> +SOCS and the Scheduler will be moving to the pre-calculated `Sky Brightness code`_ by the time version 1.0 of the combined system comes out. This is a project sanctioned model for sky brightness. Thi
If a non-LSST person is reading this, they may know know what "project sanctioned" means.  Maybe just change to "model sanctioned by the LSST Project."

2016-11-14 19:18 UTC, cathypetry commented on index.rst
> +The Scheduler Driver and Scheduler configuration topics are used by the LSST Scheduler. However, other Scheduler's are not required to use them. If configuration of another Scheduler is required, ple
"Scheduler's" should be "Schedulers"

2016-11-14 19:19 UTC, cathypetry commented on index.rst
> +SOCS currently uses the OpSim3 cloud information. A Scheduler may have it's own cloud model and ignore the information coming from SOCS. However, the observation cloud information is taken from the O
"it's" should be "its"

2016-11-14 19:27 UTC, cathypetry commented
Overall - great start!!!  It feels like you just jump into the details - which is okay if the prospective scheduler-writer already has some knowledge about how SOCS/Scheduler works already.  But if you envision that this will be a landing page or a launching pad page - then perhaps you could add a couple more lines after the first sentence and before the last sentence of the Introduction giving a larger context of what the SOCS/Scheduler does and the over all architecture.  You already have lots of references so I wouldn't replicate those, but maybe move the part about "The LSST Observatory Control System (OCS) communicates with all components via the Software Abstraction Layer (SAL)/Distributed Data Service (DDS) protocol. SOCS also communicates this way to interface with the LSST Scheduler." to the Introduction and follow up with generally what happens (or even show the diagram!) - e.g. information comes in, decisions are made, output goes out and stored in a db....  Just a few sentences - and could point to the SPIE paper too.

2016-11-14 21:39 UTC, cathypetry requested changes
All done!!

2016-11-14 21:49 UTC, cathypetry requested changes
Here is my attempt at requesting your attention.

2016-11-14 21:49 UTC, cathypetry commented on index.rst
> +:tocdepth: 1
Here is my test request for changes.

2016-11-14 21:49 UTC, cathypetry commented on index.rst
> +.. note::
Heres' another recommendation.

2016-11-15 17:13 UTC, mareuter commented on index.rst
> +:tocdepth: 1
Change not necessary.

2016-11-15 17:13 UTC, mareuter commented on index.rst
> +.. note::
Change not necessary.

2016-11-15 17:24 UTC, mareuter commented on index.rst
> +All information is currently mandatory due to the LSST Scheduler being responsible for the information. However, the new `Sims Survey Fields code`_ is destined end the need for a Scheduler to send th
You are correct. Fixed.

2016-11-15 17:26 UTC, mareuter commented on index.rst
> +The Scheduler Driver and Scheduler configuration topics are used by the LSST Scheduler. However, other Scheduler's are not required to use them. If configuration of another Scheduler is required, ple
You are correct. Fixed.

2016-11-15 17:26 UTC, mareuter commented on index.rst
> +SOCS currently uses the OpSim3 cloud information. A Scheduler may have it's own cloud model and ignore the information coming from SOCS. However, the observation cloud information is taken from the O
You are correct. Fixed.

2016-11-15 17:28 UTC, mareuter commented on index.rst
> +The Simulated Observatory Control System (SOCS) is designed to work with the LSST Scheduler. However, this does not mean that other Schedulers can't be developed and interfaced with SOCS in order to
I like what you said better as it is more positive. Changed.

2016-11-15 17:29 UTC, mareuter commented on index.rst
> +From Scheduler Topics
Sounds like a good idea. Changed.

2016-11-15 18:38 UTC, mareuter commented on index.rst
> +SOCS and the Scheduler will be moving to the pre-calculated `Sky Brightness code`_ by the time version 1.0 of the combined system comes out. This is a project sanctioned model for sky brightness. Thi
Sounds like a good clarification. Changed.

2016-11-15 18:42 UTC, mareuter commented on index.rst
> -     Caption text.
Comment looks a bit out of place, but this is fixed.

2016-11-15 18:50 UTC, mareuter commented
For the final large comment, I moved the suggested line into the opening paragraph and included a citation to the SOCS SPIE paper.

2016-11-16 18:45 UTC, cathypetry approved these changes

2016-11-16 19:36 UTC, merged